### ISSUE TITLE
epub is missing images ?

### ISSUE THREAD

**Issue by rabidgremlin** [dunyakirkali/letterpress#1]
Just tried this sample and the epub file seems to have broken images. Tried it in two different reader. PDF output seems good.

**Comment by dunyakirkali** [comment]
Related to https://github.com/asciidoctor/asciidoctor-epub3/issues/22

**Comment by dunyakirkali** [comment]
@rabidgremlin thank you for noticing.

I just fixed the issue by moving book.adoc to the root of the project since asciidoctor-epub3 is not able to handle images that live outsude the source directory (where book.adoc previously was)
